### ISSUE TITLE
Github pre-receive hook to ensure review is not skipped

### ISSUE THREAD

**Issue by johanoskarsson** [reenhanced/gitreflow#121]
I'd like to enforce that the reflow review process is followed by disallowing merging to master without reviews (unless the user forces it explicitly during an emergency).

Would this be a feature that could live in reflow?

**Comment by codenamev** [comment]
Can you describe the use case?

In a generic agile workflow, master can be pushed to at anytime, and it's the responsibility of the feature branches to pick up on any changes before merging back down to master.  That's one reason we do a `git pull origin <base-branch>` before the `delver` command merges down your feature branch.

@nhance and I have been discussing the possibility of abstracting workflows so that anyone can customize the process much the way you can do with capistrano.  Not sure of the timeline on that though.

**Comment by johanoskarsson** [comment]
The use case is to ensure that all the commits to master have in fact followed the workflow (new branch, pull request, reviewed etc). Both because some people might forget or simply think that it won't do any harm to sneak through a few commits.

**Comment by nhance** [comment]
I think this is a great idea, but it's beyond what `git reflow` can do. Reflow is an extension of the `git` command and designed to be a lightweight tool to help developers reduce the risk of slipping up. Adding hard restrictions like this seems like it might be a better fit for a system like beanstalkapp.com ?

**Comment by codenamev** [comment]
Closing this out.
