### ISSUE TITLE
Running setup multiple times will create multiple entries in .gitconfig

### ISSUE THREAD

**Issue by jtietema** [reenhanced/gitreflow#203]
When running `git reflow setup` multiple times, the setup appends a line for every run in `.gitconfig` making it look like this.

```
[include]
	path = /Users/Jeroen.Tietema/.gitconfig.reflow
	path = /Users/Jeroen.Tietema/.gitconfig.reflow
	path = /Users/Jeroen.Tietema/.gitconfig.reflow
	path = /Users/Jeroen.Tietema/.gitconfig.reflow
	path = /Users/Jeroen.Tietema/.gitconfig.reflow
	path = /Users/Jeroen.Tietema/.gitconfig.reflow
```

Would be nice if it would check if the line is already there.

**Comment by Shalmezad** [comment]
Think I found the issue, will fix it later tonight if someone doesn't beat me to it. :)

In the setup command (lib/git_reflow/workflows/core.rb), it's checking for:
`File.exist?(GitReflow::Config::CONFIG_FILE_PATH) or existing_git_include_paths.include?(GitReflow::Config::CONFIG_FILE_PATH)`

Here is the existing git_include_paths after running it once: 
`/Users/shalmezad/.gitconfig.reflow`

Here is the CONFIG_FILE_PATH: 
`$HOME/.gitconfig.reflow`

So `include?` didn't work, and `File.exist?` doesn't work with environment variables (learn something new every day):
`File.exist?("$HOME/.gitconfig.reflow")`

Definitely don't want to do a system call to evaluate it, especially since it should be in `ENV`, so leaning towards something like this: https://gist.github.com/steakknife/4606598

**Comment by jtietema** [comment]
Awesome! Thanks for fixing this 😄
