### ISSUE TITLE
git reflow status returns with 401 - Bad credentials

### ISSUE THREAD

**Issue by abhishek77in** [reenhanced/gitreflow#219]
How to setup git reflow afresh?

Something is wrong with my git reflow setup. Few commands work for me and few don't. Eg. I can do `git reflow start` but cannot do `git reflow deliver` or `git reflow status`.

I keep getting Bad credentials and running `git reflow setup` again does not help.

**Comment by codenamev** [comment]
Please include more detailed output both of the working commands and the non-working commands.  Also, what version are you on (`git reflow --version`)?

**Comment by codenamev** [comment]
Closing this for now.  If you still have this issue, please provide more details of the output.

**Comment by codenamev** [comment]
Yes, you should be able to `gem uninstall git_reflow`.  I also recommend opening up `~/.gitconfig.reflow` and deleting the `[github]` section.  Also, since GitHub no longer supports managing oauth-tokens via their API, you'll have to manually remove any `git-reflow` labeled tokens listed in your [Personal access tokens](https://github.com/settings/tokens).

Once you've done all that, you can re-run `git reflow setup` as if it were never installed.

> non-working commands: git reflow deliver

Please paste the output in your terminal from running this command.

**Comment by abhishek77in** [comment]
@codenamev Thanks!

Error when using `git reflow deliver`:

```
error: GET https://api.github.com/repos/abhishek77in/azurite/pulls?access_token=ee787f2828af84a2bedd59fd3235c9d7a92cd4d1&base=master&head=abhishek77in%3Aoptimize-pdf-generation&state=open: 401 - Bad credentials
See: https://developer.github.com/v3
```

**Comment by abhishek77in** [comment]
@codenamev The uninstall did not work for me. It still remembers that I have a Github account setup etc.
I ran `gem uninstall git_reflow` and deleted `~/.gitconfig.reflow`.

**Comment by codenamev** [comment]
If `git config --get-all github.oauth-token` returns anything, then `git-reflow setup` will give you that message.  So if you ran the `--replace-all` I mentioned, then chances are that's what it's telling you.  Does `deliver` work now?

**Comment by abhishek77in** [comment]
I understand now, thanks a ton!

**Comment by abhishek77in** [comment]
@codenamev Updated the gem and got reflow to work. Sorry about the late response, thanks a lot for looking into this.
