### ISSUE TITLE
Command to edit default commit format

### ISSUE THREAD

**Issue by eaigner** [reenhanced/gitreflow#51]
During the setup there was no option to specify a default commit format. I apologise in advance if I overlooked such a feature.

In my case I want to remove all the squashed commit information from the default commit text, since this info is not relevant in any case and just takes up space.

**Comment by codenamev** [comment]
@bakesteve sure give it a go!

Ah, yeah we've only tested gitreflow on Ubuntu and OSX...

We've recently refactor the file you referenced to here: https://github.com/reenhanced/gitreflow/blob/master/lib/git_reflow/git_helpers.rb#L60

I imagine you're getting that error message since the file `./tmp_squash_msg` doesn't exist yet.  Adding something like `touch ./tmp_squash_msg` before that gets run should fix your issue.

Let me know where I can help.

**Comment by codenamev** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;lBFjnE8M&#x2F;30-turn-default-merge-commit-message-into-template"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Turn default merge commit message into template</a>

**Comment by Shalmezad** [comment]
Going to take a look at this later this week if you don't mind.

Any particular way you want this done?
(I'm thinking uses variable in ~/.gitconfig.reflow if it's available [will add default on setup], otherwise shows a warning and uses default, document the mustache variables available in the README, etc).

**Comment by codenamev** [comment]
That all sounds good.  I'm a _little_ hesitant on adding `mustache` as a dependency for this as it's such a small feature.  Maybe start with it and then see if it's easy enough to implement without it?

**Comment by Shalmezad** [comment]
Don't think we'll need the `mustache` gem unless you see value in using it. 
Will have to do some digging to make sure this will work fine, but I'm leaning towards a gsub paired with self.send (evaluate mustache variables as calls), or having a preset dictionary of possible values that can be used.
```
def blah
  return "hello"
end
your_commit_message = "this will say {{blah}}"
your_commit_message.gsub(/\{\{([a-zA-Z_]+[a-zA-Z0-9_]*)\}\}/){self.send($1)}
```
`"this will say hello"`

**Comment by codenamev** [comment]
This was completed with 8eb339171a51a460ba4d635fd069c2f7b608cce4.

It introduced a new commit message template (MERGE_COMMIT_TEMPLATE ), in addition to the PULL_REQUEST_TEMPLATE (which is loaded from the standard paths that GitHub expects them), and adds the ability to define `{{ }}` template tags in both this new template and PR template. Anything inside of the `{{ }}` is sent to the GitReflow module using `public_send`; so any method available to GitReflow is available to templates
